# 1.Create a one-dimensional ndarray object with a length of 10 and all 0s, and then make the fifth element equal to 1

In [11]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import matplotlib.pyplot as plt

%matplotlib inline
s1 = np.zeros(shape = 10)
s1
s1[4] = 1
s1

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 2. Create an ndarray object elements from 10 to 49

In [16]:
np.random.randint(10,50,size=10)
np.linspace(10,49,10)
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

# 3. Reverse the position of all the elements of question 2

In [17]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

# 4.Use np.random.random to create a 10*10 ndarray object and print out the largest and smallest elements

In [23]:
a4 = np.random.random(size = (10,10))
a4
zmin,zmax=a4.min(),a4.max()
zmin,zmax

(0.007345728073321678, 0.9834342073236058)

# 5.Create a 1010 ndarray object, and the matrix boundary is all 1, and the inside is all 0 

In [22]:
import numpy as np
nd = np.zeros(shape = (10, 10),dtype = np. int8)
nd[[0,9]] = 1

nd[:,[0,9]] = 1
nd

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int8)

# 6.Create a 5*5 matrix with each row from 0 to 4 

In [25]:
a = [0,1,2,3,4]
nd = np.array(a*5)
nd.reshape(5,5)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

# 7.Create an arithmetic sequence of length 12 between (0, 1) 

In [26]:
np.linspace(0,1,12)

array([0.        , 0.09090909, 0.18181818, 0.27272727, 0.36363636,
       0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182,
       0.90909091, 1.        ])

# 8.Create a random array of length 10 and sort

In [34]:
a8 = np.random.random(10)
a8
np.sort(a8)
a8.argsort()
a8[a8.argsort()]

array([0.00400603, 0.07422144, 0.09471397, 0.26896984, 0.38810247,
       0.6089411 , 0.61945408, 0.83662853, 0.90352872, 0.93581637])

   #      9.      Create a random array of length 10 and replace the maximum value with 0

In [123]:
nd = np.random.randint(0,10,size = 10)
display(nd)
index_max= nd.argmax()
nd[index_max]
all_index_max = np.argwhere(nd==nd[index_max]).reshape(-1)
all_index_max
nd[all_index_max]=-100
nd

array([9, 3, 4, 0, 8, 8, 7, 8, 6, 9])

array([-100,    3,    4,    0,    8,    8,    7,    8,    6, -100])

# 10. How to sort a 5*5 matrix according to the third column?

In [128]:
n10=np.random.randint(0,100,size=(5,5))
n10
n10[:,2]
np.argsort(n10[:,2])
n10[np.argsort(n10[:,2])]

array([[17, 92,  5, 27, 69],
       [67, 20, 20, 31, 33],
       [42, 74, 21, 60, 11],
       [ 2, 82, 47, 37, 70],
       [53, 28, 49, 90, 98]])

# 11.Given a 4-dimensional matrix, how to get the sum of the last two dimensions?

In [67]:
n11=np.random. randint(0, 100, size=(2,3,3,3))
n11
n11.sum(axis=(2,3))
n11. sum(axis=(-1,-2))

array([[586, 333, 380],
       [520, 428, 474]])

# 12. Given an array [1, 2, 3, 4, 5], how to get a new array with 3 zeros inserted between each element of this array?

In [75]:
nd1 = np.arange(1,6)
nd2 = np.zeros(shape=17,dtype=int)
nd2[::4] = nd1
nd2

array([1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5])

# 13.Given a two-dimensional matrix, how to exchange the elements of two rows?

In [83]:
np13=np.random.randint(0,100,size=(3,3))
np13

array([[92, 16, 15],
       [91, 29, 17],
       [41, 72, 91]])

# 14.Create a random array with a length of 100,000, use two methods to square it, and compare the time taken

In [91]:
n14=np.random.random(size=100000)
n14
n14=np.random.randint(0,100000,(5))
n14
%timeit np.power(n14,3)
%timeit n14**3
n14_2=np.dot(n14,n14)
%timeit np.dot(n14_2,n14)

1.36 µs ± 86.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
1.43 µs ± 79.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
3.69 µs ± 209 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 15.Create a 53 random matrices and a 32 Random matrix, find matrix product

In [95]:
n15_53=np.random.randint(0,100,size=(5,3))
n15_53
n15_32 = np.random.randint(0,100,(3,2))
n15_32
np.dot(n15_53,n15_32)

array([[ 4046, 10632],
       [12698, 17387],
       [ 9977, 17991],
       [ 4428, 12004],
       [10554, 16121]])

# 16.The elements of each row of the matrix are subtracted from the average value of the row

In [99]:
n16 = np.random.randint(0,10,(3,3))
n16
n16_1 = n16.mean(axis=1).reshape(3,1)
n16_1
n16-n16_1

array([[-0.33333333, -1.33333333,  1.66666667],
       [ 0.33333333,  0.33333333, -0.66666667],
       [ 0.33333333, -0.66666667,  0.33333333]])

# 17.Print out the following function (required to use np.zeros to create an 8*8 matrix):

* [[0 1 0 1 0 1 0 1]
* [1 0 1 0 1 0 1 0]
* [0 1 0 1 0 1 0 1]
* [1 0 1 0 1 0 1 0]
* [0 1 0 1 0 1 0 1]
* [1 0 1 0 1 0 1 0]
* [0 1 0 1 0 1 0 1]
* [1 0 1 0 1 0 1 0]]

In [100]:
nd=np.ones(shape = (8,8),dtype=int)
nd[::2,::2]=0
nd[1::2,1::2]=0
nd

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# 18.Regularize a 55 random matrix [Regular concept: Assuming that a is an element in the matrix, max/min are the maximum and minimum values ​​of the matrix elements respectively, then a = (a-min)/(max -min)] 

In [106]:
n18 = np.random.randint(0,100,(5,5))
n18
nmax,nmin=n18.max(),n18.min()
nmax,nmin
n18=(n18-nmin)/(nmax-nmin)
n18

array([[0.18556701, 0.79381443, 0.7628866 , 0.        , 0.16494845],
       [0.59793814, 0.06185567, 0.55670103, 0.56701031, 0.87628866],
       [0.50515464, 0.71134021, 0.09278351, 0.02061856, 0.30927835],
       [0.86597938, 0.72164948, 0.60824742, 1.        , 0.77319588],
       [0.05154639, 0.48453608, 0.92783505, 0.71134021, 0.32989691]])

# 19.Convert a one-dimensional array into a binary representation matrix. E.g [1,2,3] is converted to
* [[0,0,1],
* [0,1,0],
* [0,1,1]]

In [111]:
1 and 0
1 or 1
1 & 2

0

# 20 realize the bubble sort method

* n=[19,60,66,71,54,57,1,24,82,39]


In [112]:
n20=[19,60,66,7154,57,1,24,82,39]
for i in range(len(n20)-1):
    for j in range (len(n20)-i-1):
        if  n20[j]>n20[j+1]:
            n20[j],n20[j+1]=n20[j+1],n20[j]
n20

[1, 19, 24, 39, 57, 60, 66, 82, 7154]